select * from customer

--Total revenue generated by male vs female customers
select gender, SUM(purchase_amount) as revenue from customer group by gender


--Customers use discount but still spend more than avg purchaase amount
select customer_id, purchase_amount from customer 
where discount_applied ='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


--Top 5 products with highest avg review rating
select item_purchased, ROUND(avg(review_rating::numeric),2) from customer 
group by item_purchased order by avg(review_rating) desc limit 5


--Compare the avg Purchase amount between Standard and Express Shipping
select shipping_type, ROUND(avg(purchase_amount),2) as "Avg Purchase amount" from customer 
where shipping_type in ('Standard', 'Express') group by shipping_type


--Do subscribed customers spend more? Compare avg spend and total revenue between subscribers and non subscribers
select subscription_status, count(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as Avg_Spent, 
ROUND(sum(purchase_amount),2) as Total_Revenue
from customer
group by subscription_status
order by Total_Revenue, Avg_Spent desc


--5 products with highest percentage of purchases with discount applied
select item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc limit 5


--Segment customers based on total no of previous purchases and show count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New' 
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning' 
	ELSE 'Loyal' 
	END as customer_segment
from customer
)
select customer_segment, count (*) as "Number of Customers"
from customer_type
group by customer_segment


--top 3 most purchased products within each category
with item_counts as(
select category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by COUNT(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;


--are customers who are repeated buyers also likely to subscribe(more than 5 purchases)?
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--Revenue generated by each age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC
